[package]
name = "mazes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.14.9", features = ["png"] }
png = "0.17.2"
rand = "0.8.4"
