[package]
name = "mazes"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.9.0", features = ["small_rng"] }
rand_seeder = "0.4.0"